fix: Implement exception test cases access issue [#70]
dataswap/core pull request #101
Opened 2023-09-05 04:08 UTC by lovel8

## Related Issues

close #70 

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2023-09-06 00:36 UTC, siriusyim requested changes

2023-09-06 00:36 UTC, siriusyim commented on test/v0.8/uinttests/core/access/AcceptOwnership.t.sol
> +import "test/v0.8/testcases/core/access/AcceptOwnershipTestSuite.sol";
Change the import format.

2023-09-06 00:36 UTC, siriusyim commented on test/v0.8/uinttests/core/access/CheckRole.t.sol
> +import "test/v0.8/testcases/core/access/CheckRoleTestSuite.sol";
Change the import format.

2023-09-06 00:36 UTC, siriusyim commented on test/v0.8/uinttests/core/access/GrantRole.t.sol
> +import "test/v0.8/testcases/core/access/GrantRoleTestSuite.sol";
Change the import format.

2023-09-06 00:36 UTC, siriusyim commented on test/v0.8/uinttests/core/access/RenounceOwnership.t.sol
> +import "test/v0.8/testcases/core/access/RenounceOwnershipTestSuite.sol";
Change the import format.

2023-09-06 00:36 UTC, siriusyim commented on test/v0.8/uinttests/core/access/RenounceRole.t.sol
> +import "test/v0.8/testcases/core/access/RenounceRoleTestSuite.sol";
Change the import format.

2023-09-06 00:36 UTC, siriusyim commented on test/v0.8/uinttests/core/access/RevokeRole.t.sol
> +import "test/v0.8/testcases/core/access/RevokeRoleTestSuite.sol";
Change the import format.

2023-09-06 00:36 UTC, siriusyim commented on test/v0.8/uinttests/core/access/TransferOwnership.t.sol
> +import "test/v0.8/testcases/core/access/TransferOwnershipTestSuite.sol";
Change the import format.

2023-09-07 01:01 UTC, siriusyim approved these changes

2023-09-08 03:53 UTC, waynewyang approved these changes

2023-09-08 03:53 UTC, merged