fix: Implement getCarSize method in storage [#72]
dataswap/core pull request #104
Opened 2023-09-06 02:46 UTC by lovel8

## Related Issues

close #72 

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2023-09-07 01:29 UTC, siriusyim requested changes

2023-09-07 01:29 UTC, siriusyim commented on src/v0.8/module/storage/Storages.sol
> +        return carstore.getCarSize(_cid);
Need to check if the car exists in doneCars.

2023-09-07 02:05 UTC, lovel8 commented
@siriusyim Have done

2023-09-07 03:52 UTC, siriusyim approved these changes

2023-09-08 03:41 UTC, waynewyang approved these changes

2023-09-08 03:41 UTC, merged