fixed: implement matching exception uint test[#43]
dataswap/core pull request #111
Opened 2023-09-08 07:22 UTC by siriusyim

update bidding exception test

update close exception test

update pause exception test

update resume exception test

## Related Issues

close #43 

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2023-09-08 10:45 UTC, lovel8 requested changes

2023-09-08 10:45 UTC, lovel8 commented on test/v0.8/helpers/module/matching/MatchingsHelpers.sol
> +        (bytes32[] memory cars, ) = getDatasetCarsAndCarsCount(
getDatasetCarsAndCarsCount pass a specified type parameter, but hardcode DatasetType.DataType.MappingFiles internally

2023-09-08 10:45 UTC, lovel8 commented on test/v0.8/testcases/module/matching/PublishMatchingTestSuite.sol
> +        bytes32[] memory cars = new bytes32[](carsCount);
No need to allocate memory here. If you need to copy the data value to new memory, you cannot use it like this.

2023-10-08 07:14 UTC, Kennynauh approved these changes

2023-10-08 07:19 UTC, lovel8 approved these changes

2023-10-08 07:20 UTC, merged