Feat/data trading fee
dataswap/core pull request #232
Opened 2024-01-27 08:18 UTC by lovel8

## Related Issues

close

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2024-01-29 14:17 UTC, waynewyang requested changes
pls rebase

2024-01-29 15:07 UTC, siriusyim requested changes

2024-01-29 15:07 UTC, siriusyim commented on src/v0.8/core/finance/library/DataTradingFeeLIB.sol
> +            // 2. Get payees
step 3 =>3. Get payees

2024-01-29 15:07 UTC, siriusyim commented on src/v0.8/core/finance/library/DataTradingFeeLIB.sol
> +            // 3. Get amounts
=> // 4. Get amounts

2024-01-30 05:59 UTC, siriusyim approved these changes

2024-01-31 08:16 UTC, waynewyang approved these changes

2024-01-31 08:16 UTC, merged