feat: 🎸 Replace old escrow contract
dataswap/core pull request #261
Opened 2024-02-02 07:08 UTC by lovel8

✅ Closes: #246

## Related Issues

close

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2024-02-18 14:30 UTC, waynewyang commented
@lovel8  pls rebase
 @siriusyim  pls review this PR

2024-02-19 08:50 UTC, siriusyim requested changes

2024-02-19 08:50 UTC, siriusyim commented on src/v0.8/core/finance/base/Base.sol
> +contract Base is Initializable, UUPSUpgradeable, RolesModifiers {
Add the 'abstract' keyword

2024-02-19 08:50 UTC, siriusyim commented on src/v0.8/module/dataset/Datasets.sol
> +        //     /// TODO: Add waitEscrow process(https://github.com/dataswap/core/issues/254)
remove waitEscrow

2024-02-19 08:50 UTC, siriusyim commented on src/v0.8/module/dataset/DatasetsProof.sol
> -    ///@notice Submit proof for a dataset
This piece of code would be more appropriate at this location

2024-02-19 08:53 UTC, lovel8 commented on src/v0.8/core/finance/base/Base.sol
> +contract Base is Initializable, UUPSUpgradeable, RolesModifiers {
#277 It has been modified

2024-02-19 08:54 UTC, siriusyim requested changes

2024-02-19 08:54 UTC, siriusyim commented on src/v0.8/module/dataset/DatasetsProof.sol
> -    )
Retain onlyDatasetState

2024-02-19 08:58 UTC, siriusyim approved these changes

2024-02-19 09:09 UTC, merged