fix: Implement storage unit test[#45]
dataswap/core pull request #97
Opened 2023-08-31 04:08 UTC by lovel8

## Related Issues

close #45 

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2023-09-05 09:01 UTC, siriusyim requested changes

2023-09-05 09:01 UTC, siriusyim commented on test/v0.8/uinttests/module/storage/setup/StorageTestSetup.sol
> +    Generator generator = new Generator();
Recommend standardizing the style for initializing state variables

2023-09-06 03:02 UTC, lovel8 commented on test/v0.8/uinttests/module/storage/SubmitStorageDealId.t.sol
> +import "test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol";
@siriusyim For situations where a large amount of symbol data needs to be imported, it is recommended to use this full import method uniformly, which will be neater

2023-09-06 03:27 UTC, siriusyim approved these changes

2023-09-08 03:29 UTC, waynewyang requested changes

2023-09-08 03:29 UTC, waynewyang commented on test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol
> +        //TODO: add getCars in matching:https://github.com/dataswap/core/issues/74
pls remove this TODO line.

2023-09-08 03:29 UTC, waynewyang commented on test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol
> +            .getMatchingTarget(_matchingId);
using `getMatchingCars`.

2023-09-08 03:29 UTC, waynewyang commented on test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol
> +            .getMatchingTarget(_matchingId);
remove TODO, and using getMatchingCars.

2023-09-08 03:29 UTC, waynewyang commented on test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol
> +            .getMatchingTarget(_matchingId);
remove TODO, and using getMatchingCars.

2023-09-08 03:29 UTC, waynewyang commented on test/v0.8/uinttests/module/storage/SubmitStorageDealId.t.sol
> +import "test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol";
pls using format: import {* ,* ,*} from .

2023-09-08 06:26 UTC, lovel8 commented
@waynewyang Have done

2023-09-08 07:27 UTC, waynewyang approved these changes

2023-09-08 07:27 UTC, merged