fix: Implement dataset exception uint test [#42]
dataswap/core pull request #99
Opened 2023-09-04 07:05 UTC by lovel8

## Related Issues

close #42 

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2023-09-06 01:02 UTC, siriusyim requested changes

2023-09-06 01:02 UTC, siriusyim commented on test/v0.8/uinttests/module/dataset/Approve.t.sol
> +import "test/v0.8/testcases/module/dataset/ApproveTestSuite.sol";
Change the import format.

2023-09-06 01:02 UTC, siriusyim commented on test/v0.8/uinttests/module/dataset/ApproveMetadata.t.sol
> +import "test/v0.8/testcases/module/dataset/ApproveMetadataTestSuite.sol";
Change the import format.

2023-09-06 01:02 UTC, siriusyim commented on test/v0.8/uinttests/module/dataset/Reject.t.sol
> +import "test/v0.8/testcases/module/dataset/RejectTestSuite.sol";
Change the import format.

2023-09-06 01:02 UTC, siriusyim commented on test/v0.8/uinttests/module/dataset/RejectMetadata.t.sol
> +import "test/v0.8/testcases/module/dataset/RejectMetadataTestSuite.sol";
Change the import format.

2023-09-06 01:02 UTC, siriusyim commented on test/v0.8/uinttests/module/dataset/SubmitMetadata.t.sol
> +import "test/v0.8/testcases/module/dataset/SubmitMetadataTestSuite.sol";
Change the import format.

2023-09-06 01:02 UTC, siriusyim commented on test/v0.8/uinttests/module/dataset/SubmitProof.t.sol
> +import "test/v0.8/testcases/module/dataset/SubmitProofTestSuite.sol";
Change the import format.

2023-09-06 01:02 UTC, siriusyim commented on test/v0.8/uinttests/module/dataset/SubmitVerification.t.sol
> +import "test/v0.8/testcases/module/dataset/SubmittVerificationTestSuite.sol";
Change the import format.

2023-09-06 03:53 UTC, lovel8 commented
@siriusyim Have done

2023-09-07 01:07 UTC, siriusyim approved these changes

2023-09-08 03:55 UTC, waynewyang approved these changes

2023-09-08 03:55 UTC, merged